name: Flaskex Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1

    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ env.GIT_COMMIT_SHORT_SHA }} .  

    - name: Verify Docker Image
      run: docker images

    - name: Doker Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} 

    - name: Doker Push
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/flaskex:${{ env.GIT_COMMIT_SHORT_SHA }}
